Feature/xm cloud embedded personalize faq
Sitecore/developer-portal pull request #367
Opened 2023-01-05 16:42 UTC by dylanyoung-dev

This is the implementation of the recently released Sitecore XM Cloud with Embedded Personalization FAQ into the developer portal.  I've also included links on the Learn Composable DXP section, and into the XM Cloud and CDP/Personalize product pages to link to this new FAQ as well.

## Description / Motivation

Added 4 new images plus a bunch of new markdown files to represent the FAQ.  All documentation and no functional changes.  I also updated existing Markdown files to link to the new FAQ document from relevant sections.

## How Has This Been Tested?

This change was tested locally.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [X] Documentation update (non-breaking change; modified files are limited to the `/data` directory or other markdown files)

## Checklist:

- [X] I have read the Contributing guide.
- [X] My code/comments/docs fully adhere to the Code of Conduct.
- [ ] My change is a code change.
- [X] My change is a documentation change and there are NO other updates required.
- [ ] My change has new or updated images which are stored in the `/public/images` folder that need to be migrated to Sitecore DAM

2023-01-06 18:03 UTC, dylanyoung-dev commented
I've discussed and shown the preview to Ahmed, and he thinks it looks good.  So off to final review by the team.

2023-01-08 14:00 UTC, jst-cyr requested changes
Below, please find the issues I noticed during my review.

**NOTE:** Reviewed on the [preview site](https://developer-portal-mj1mfjjhb-sitecoretechnicalmarketing.vercel.app/)

* Looks like Markdown for the Experience Edge link is broken on [this question](https://developer-portal-mj1mfjjhb-sitecoretechnicalmarketing.vercel.app/learn/faq/xm-cloud-embedded-personalization/feature-matrix#what-features-do-i-get-if-i-license-full-sitecore-personalize-in-addition-to-xm-cloud)
   * For that question, you may also want to use the 'latest' doc link so it doesn't go out of date. i.e. https://doc.sitecore.com/xp/en/developers/hd/latest/sitecore-headless-development/sitecore-experience-edge-for-xm.html
* There is a duplicate sentence in this [Site Insights answer](https://developer-portal-mj1mfjjhb-sitecoretechnicalmarketing.vercel.app/learn/faq/xm-cloud-embedded-personalization/feature-matrix#what-are-the-analytics-capabilities-provided-by-xm-cloud).
   * You may also want to use markdown here to link out to the docs.
* On this (embedded personalization question](https://developer-portal-mj1mfjjhb-sitecoretechnicalmarketing.vercel.app/learn/faq/xm-cloud-embedded-personalization/feature-matrix#what-can-i-personalize-with-xm-cloud-personalization) it says "with Personalize", but the question seems to imply using XM Cloud Personalization (which elsewhere you call embedded personalization). I think the terms here might need to be updated for consistency so it is clear whether this is about embedded personalization or Sitecore Personalize.
* On this [migration question](https://developer-portal-mj1mfjjhb-sitecoretechnicalmarketing.vercel.app/learn/faq/xm-cloud-embedded-personalization/migrations-and-upgrades#can-i-migrate-my-current-sitecore-10x-headless-jss-implementation-personalization-rules-variants-and-actions-to-sitecore-xm-cloud-personalizationpersonalize) it mentions the acronym SXP but this acronym hasn't been introduced in this page yet. I recommend writing it out in full.
* On this [migration question](https://developer-portal-mj1mfjjhb-sitecoretechnicalmarketing.vercel.app/learn/faq/xm-cloud-embedded-personalization/migrations-and-upgrades#can-i-migrate-my-xm-cloud-embedded-personalization-to-sitecore-personalize-license) it is written "XM-Cloud" instead of "XM Cloud"
* On this [migration question about contacting sales](https://developer-portal-mj1mfjjhb-sitecoretechnicalmarketing.vercel.app/learn/faq/xm-cloud-embedded-personalization/migrations-and-upgrades#whom-should-i-contact-in-i-need-to-acquire-capabilities-of-a-full-personalize-license) it mentions the feature set described above, which I guess is from when this was a PDF. Since that feature set is not on this page on the portal, this text doesn't make sense. I think you may want to direct link to the question in the FAQ that answers this.
* For [this DevEx question](https://developer-portal-mj1mfjjhb-sitecoretechnicalmarketing.vercel.app/learn/faq/xm-cloud-embedded-personalization/developer-experience#what-does-embedded-personalization-mean-for-developers-and-technicians) it references Dylan's video, but the markdown seems to have an extra playlist link that is after the original video link.
   * Also, I believe @markvanaalst added support for MDX, so you may be able to embed the video here. Check with Mark on if this is possible.

2023-01-09 08:13 UTC, markvanaalst commented
> * Also, I believe @markvanaalst added support for MDX, so you may be able to embed the video here. Check with Mark on if this is possible.

Embedding YouTube videos is indeed possible. I just added support for embedding playlists as well and took the liberty of adding the component to the DevEx question.

FYI: You can embed video's and/or playlists like this:

**Single video:**
`<YouTube youTubeId="LdxNRo22Vf8" />`

**Playlist:**
`<YouTube youTubeId="PL1jJVFm_lGnzqYagW1UahIBeqTIYSBQMc" isPlayList={true} playlistCoverId="LdxNRo22Vf8" />`

Note: playlistCoverId is the id of the video from which its cover image will be used

2023-01-10 11:44 UTC, markvanaalst approved these changes

2023-01-11 17:29 UTC, jst-cyr approved these changes

2023-01-11 17:33 UTC, merged