Added numerous Search fixes/improvements
Sitecore/developer-portal pull request #459
Opened 2023-05-23 01:11 UTC by robearlam

This PR adds a number of fixes and improvements to the Search Implementation

- Removed incorrect event call in _app.tsx
- Correctly configured view events in Search Results Click event
- Added term highlighting in PreviewSearch Input
- Add restrictions on which sources are being searched, controlled via an ENV VAR. This will allow us to add new indexes and test locally before updating the prod value and putting it live.

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation update (non-breaking change; modified files are limited to the `/data` directory or other markdown files)

## Checklist:
- [x] I have read the Contributing guide.
- [x] My code/comments/docs fully adhere to the Code of Conduct.
- [x] My change is a code change.
- [ ] My change is a documentation change and there are NO other updates required.
- [ ] My change has new or updated images which are stored in the `/public/images` folder that need to be migrated to Sitecore DAM

2023-05-25 17:28 UTC, jst-cyr requested changes
Term highlighting only seems to work if the term is in the description. There is no visual change when it is in the title.
![image](https://github.com/Sitecore/developer-portal/assets/4146192/6a174029-221c-4033-90f0-a8067930075e)

2023-05-25 23:54 UTC, robearlam commented
Correct, this is intentional. We only do term highlighting on the description field on the main results listing as well, this PR is to bring the Preview Search in line with that.

If we want to add Term Highlighting to the titles as well, we can do that in a different PR as its will be a change to how it functions currently and we'll need to figure out how to highlight it in the UI as the title is already bold.

2023-05-26 11:38 UTC, jst-cyr commented
> Correct, this is intentional. We only do term highlighting on the description field on the main results listing as well, this PR is to bring the Preview Search in line with that.

Gotcha, then I didn't see any issues!

2023-05-26 11:38 UTC, jst-cyr approved these changes

2023-05-28 23:57 UTC, merged