Added tab trapping to nav.
Sitecore/developer-portal pull request #54
Opened 2021-09-21 17:58 UTC by bhgeorge

2021-09-21 19:10 UTC, andershopkins requested changes
**Desktop**

- Keyboard functionality is great
- However, things get weird when using a mouse
   - Need proper handling click outside
   - Need to NOT reopen the current menu when user clicks the menu item, should just close the related menu item.
- Add a "Close Menu" button that appears only on focus in the menu dropdown thingies, for **desktop only**. 
   
 **Mobile**
 - Cannot focus to Search / Logo / Hamburger

2021-09-22 17:00 UTC, bhgeorge commented
@andershopkins For the `NavMenu` I updated the trap to include the toggleable main item as it made the rest of the trap 1000x easier to deal with. Because of this I wasn't sure if I should _also_ include the sr-focus close button.

If you feel like we should still have that as well, then I can add it in quick.

2021-09-22 18:53 UTC, andershopkins commented
> @andershopkins For the `NavMenu` I updated the trap to include the toggleable main item as it made the rest of the trap 1000x easier to deal with. Because of this I wasn't sure if I should _also_ include the sr-focus close button.
> 
> If you feel like we should still have that as well, then I can add it in quick.

This will cause problems on mobile when there _is_ a back button AND the menu sits over the top of the nav item.

2021-09-23 13:07 UTC, andershopkins commented
There is an array of problem while using `focus-trap-react`.

- Focus will be trapped in the `<nav>` element and can only be escaped with `esc` keypresses, as the `FocusTrap` is wrapping the entire `<header>` but that trap should only be present in mobile.
- I have yet to figure out a feasible path, at least in functional components, to simply disable this wrapping `FocusTrap` at different screen sizes.
- I did a quick POC on separating `mobile` and `desktop` navigations, but then we run into the issue with the plugin while switching between screen sizes where it errors out because it has no `focusable` element (as the `desktop` or `mobile` nav has gone to display none). 
- Hooks for mounting/unmounting `mobile` and `desktop` navigation will not play nicely with SSR/SSG so that's not really a viable option (though it would solve the `FocusTrap` problems.

I'm sure we can figure this out, but this branch isn't in a state close enough to merge so I'm closing this PR, but leaving the branch (in addition to v2).

2021-09-23 13:07 UTC, closed without merging