ACC-76 Updates "template.module.json" guide
Sitecore/developer-portal pull request #670
Opened 2024-03-12 19:20 UTC by crhistianramirez

2024-03-12 19:27 UTC, GuitarRich requested changes

2024-03-12 19:27 UTC, GuitarRich commented on apps/devportal/data/markdown/pages/learn/accelerate/xm-cloud/pre-development/sprint-zero/setup-content-serialization/template.module.json.md
> +      "allowedPushOperations": "Create"
Change from `Create` to `CreateOnly`

2024-03-12 19:27 UTC, GuitarRich commented on apps/devportal/data/markdown/pages/learn/accelerate/xm-cloud/pre-development/sprint-zero/setup-content-serialization/template.module.json.md
> +            "allowedPushOperations": "Create"
Change `Create` to `CreateOnly`

2024-03-12 20:20 UTC, GuitarRich requested changes
Is there a reason why the files were deleted in the `example-code` folder? That is where they should live. And the `xmcloud-build-json.md` shouldn't have been edited at all in this PR.

2024-03-13 14:22 UTC, GuitarRich requested changes

2024-03-13 14:22 UTC, GuitarRich commented on apps/devportal/data/markdown/pages/learn/accelerate/xm-cloud/pre-development/sprint-zero/setup-content-serialization/template.module.json.md
> +            "path": "/Settings",
Please update the order here, `/Settings` needs to come after `/Settings/Site Grouping` because of the rule order of SCS.

2024-03-13 16:06 UTC, crhistianramirez commented
@GuitarRich  this is ready for review

2024-03-13 16:22 UTC, GuitarRich approved these changes

2024-03-13 16:30 UTC, merged